### ISSUE TITLE
Exampels

### ISSUE THREAD

**Issue by teemiik** [RubbaBoy/NewOCR#5]
Hello. Have you tried using recognition on more complex examples, for example, on scanned passports?

**Comment by RubbaBoy** [comment]
That wouldn't work because of the poor filtering currently in place, which pretty much makes it black and white and assumed any black pixels are probably text. In the future I'd love to improve this, such as adding noose cancellation, skew fixing, etc. The current solution is in the `OCRHandle#filter` method I believe, I can't check since I'm on my phone.

**Comment by teemiik** [comment]
I can give you an adaptive filter written with opencv or you can use adaptive filters leptonica, you can then try to recognize complex text?

**Comment by RubbaBoy** [comment]
Thank you, I'm glad you like the project. I think leptonica seems like it would be a good library to use with this, since it seems to be made for exactly what is needed with this. Would you be interested in helping implement this as well? I'd be able to once I finish (Or almost finish) the next release for MS Paint IDE, and then I'd be all in for improving the OCR. Right now the buggiest part about the OCR is character detection, as it wasn't originally intended to be used with non-computer generated images.

**Comment by RubbaBoy** [comment]
I've playing around with Lept4J, and I understand how to do noise removal, binarization, etc. for the most part, but I've been looking around, and is there any resources/methods explaining how to do character segmentation with Leptonica? I can see basic shape segmentation with `pixConnCompBB`, but that's about it.

Also, do you have Discord? It seems a bit odd discussing this stuff in an issue like this.

**Comment by teemiik** [comment]
Yes I have a Discord. 

Here is described a method of segmenting characters. I have an example of implementing this method in Java.
https://github.com/DanBloomberg/leptonica/blob/master/src/recogident.c

**Comment by teemiik** [comment]
I use https://github.com/bytedeco/javacpp-presets/tree/master/leptonica.

**Comment by RubbaBoy** [comment]
Closing this issue as it was diverging from the original topic, and full natural image support is sadly being postponed most likely until v3 to get the main OCR component working properly and stable first.
Thanks for your interest in the OCR @teemiik, hopefully in the future it can fully support natural images.
